### ISSUE TITLE
[GL] Reproduce and fix NewRenderTask issues

### ISSUE THREAD

**Issue by hyazinthh** [aardvark-platform/aardvark.rendering#72]
The newer render task implementation in the GL backend still has issues with removing and adding render objects leading to `ObjectDisposedException` exceptions. It is not clear yet how to reproduce them.

Some cases (AddRemoveStress example) fixed with https://github.com/aardvark-platform/aardvark.rendering/commit/bdcbdbb87e548dc6d024d669f50f4eae05d74817

**Comment by hyazinthh** [comment]
Reproducible in ConcurrencyTest example

**Comment by hyazinthh** [comment]
The issue that could be reproduced with the ConcurrencyTest example is fixed. There still seems to be another issue that cannot be reproduced in any of the examples as far as I know.

**Comment by luithefirst** [comment]
Yes, in my application I get the following exception in a one-shot render scenario:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'CodeFragment'.
   at Aardvark.Rendering.GL.ChangeableProgram.ProgramFragment.set_Next(FSharpOption`1 n)
   at Aardvark.Rendering.GL.ChangeableProgram.ProgramFragment.Dispose()
   at Aardvark.Rendering.GL.Command.ManyObjectsCommand.Free(CompilerInfo info)
   at Aardvark.Rendering.GL.Command.OrderedCommand.Free(CompilerInfo info)
   at Aardvark.Rendering.SequentialRenderTask.Release()
```

The use case looks as follows:
1. create a sequential render task with clear + render of a locally built sg
2. run the task x3 (changing some inputs)
3. disposing of the task -> crash

The sg consists of 6 `PoolNodes` also created together with the render task. The geometries for the pool nodes are pre-allocated and managed outside of the one-shot render procedure.

This means the render program should be actually very simple as there are only 6 RenderObjects. Using a GeometryPool should actually not be causing the issue as the backend only sees the RenderObjects that abstract this away and the only difference is that it has a DrawCallBuffer and the Vertex/IndexBuffers are pre-allocated.

Do we have an example that we could quickly adapt to represent a similar scenario (not necessarily with a GeometryPool) so we can evaluate if the issue is related to a sequential render task and disposing of it?
